version: '3'
services:
  train:
    image: chandu2024/train:latest
    ports:
      - "8004:80"
    deploy:
      replicas: 3
        
  movie:
    image: chandu2024/movie:latest
    ports:
      - "8005:80"
    deploy:
      replicas: 3
    
  recharge:
    image: chandu2024/recharge:latest
    ports:
      - "8006:80"    
    deploy:
      replicas: 3
